AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  BambooHR to NovaLXP (Moodle) sync on ECS Fargate with EventBridge Scheduler,
  DynamoDB state, Secrets Manager secrets, CloudWatch Logs, and SNS notifications.

Parameters:
  ProjectName:
    Type: String
    Default: bamboohr-novalxp-sync
    Description: Prefix for named resources.
    AllowedPattern: '^[a-z0-9-]{3,32}$'
    ConstraintDescription: Use 3-32 lowercase letters, numbers, and hyphens.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC that hosts the ECS task ENI.
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnet IDs for ECS task networking.
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID attached to the ECS task.
  ScheduleExpression:
    Type: String
    Default: cron(0 2 * * ? *)
    Description: Nightly EventBridge schedule expression.
  ScheduleTimezone:
    Type: String
    Default: Europe/London
    Description: IANA timezone used by EventBridge Scheduler.
  BatchSize:
    Type: Number
    Default: 100
    Description: Records processed per run. Set to 0 for no batch limit.
    MinValue: 0
  InitialLookbackDays:
    Type: Number
    Default: 14
    Description: Lookback window used only for brand new state rows.
    MinValue: 0
  AlertEmail:
    Type: String
    Description: Email address for job completion notifications.
  BambooCompanyDomain:
    Type: String
    Description: BambooHR company domain prefix (e.g., acme for acme.bamboohr.com).
  MoodleBaseUrl:
    Type: String
    Description: NovaLXP Moodle base URL (e.g., https://training.example.com).

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ProjectName}-cluster'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}'
      RetentionInDays: 30

  StateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-state'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: StateId
          AttributeType: S
      KeySchema:
        - AttributeName: StateId
          KeyType: HASH

  BambooSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/bamboohr'
      Description: BambooHR credential placeholder. Update after deploy.
      SecretString: '{"bamboohr_api_key":"REPLACE_ME"}'

  MoodleSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/moodle'
      Description: Moodle token placeholder. Update after deploy.
      SecretString: '{"moodle_token":"REPLACE_ME"}'

  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alerts'

  AlertsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertsTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-task-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt StateTable.Arn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref BambooSecret
                  - !Ref MoodleSecret

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-task'
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: sync
          Image: !Sub '${EcrRepository.RepositoryUri}:latest'
          Essential: true
          Environment:
            - Name: DDB_TABLE
              Value: !Ref StateTable
            - Name: STATE_ID
              Value: default
            - Name: BAMBOO_COMPANY_DOMAIN
              Value: !Ref BambooCompanyDomain
            - Name: MOODLE_BASE_URL
              Value: !Ref MoodleBaseUrl
            - Name: MOODLE_AUTH
              Value: oidc
            - Name: BATCH_SIZE
              Value: !Sub '${BatchSize}'
            - Name: INITIAL_LOOKBACK_DAYS
              Value: !Sub '${InitialLookbackDays}'
            - Name: BAMBOO_SECRET_ARN
              Value: !Ref BambooSecret
            - Name: MOODLE_SECRET_ARN
              Value: !Ref MoodleSecret
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-scheduler-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: RunTaskOnCluster
                Effect: Allow
                Action: ecs:RunTask
                Resource: !Sub 'arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${ProjectName}-task:*'
                Condition:
                  ArnEquals:
                    ecs:cluster: !GetAtt EcsCluster.Arn
              - Sid: PassTaskRoles
                Effect: Allow
                Action: iam:PassRole
                Resource:
                  - !GetAtt TaskExecutionRole.Arn
                  - !GetAtt TaskRole.Arn
                Condition:
                  StringEquals:
                    iam:PassedToService: ecs-tasks.amazonaws.com

  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub '${ProjectName}-nightly'
      Description: Nightly BambooHR to NovaLXP sync
      ScheduleExpression: !Ref ScheduleExpression
      ScheduleExpressionTimezone: !Ref ScheduleTimezone
      State: ENABLED
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt EcsCluster.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        EcsParameters:
          TaskDefinitionArn: !Ref TaskDefinition
          LaunchType: FARGATE
          PlatformVersion: LATEST
          TaskCount: 1
          NetworkConfiguration:
            AwsvpcConfiguration:
              AssignPublicIp: ENABLED
              Subnets: !Ref SubnetIds
              SecurityGroups:
                - !Ref SecurityGroupId

  TaskSucceededRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-task-succeeded'
      Description: Publish clean success notification when ECS task exits with code 0
      EventPattern:
        source:
          - aws.ecs
        detail-type:
          - ECS Task State Change
        detail:
          clusterArn:
            - !GetAtt EcsCluster.Arn
          lastStatus:
            - STOPPED
          containers:
            exitCode:
              - 0
      Targets:
        - Id: AlertsTopicSuccessTarget
          Arn: !Ref AlertsTopic
          Input: !Sub '"${ProjectName}: BambooHR->NovaLXP sync SUCCEEDED."'

  TaskFailedRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-task-failed'
      Description: Publish clean failure notification when ECS task exits non-zero
      EventPattern:
        source:
          - aws.ecs
        detail-type:
          - ECS Task State Change
        detail:
          clusterArn:
            - !GetAtt EcsCluster.Arn
          lastStatus:
            - STOPPED
          containers:
            exitCode:
              - anything-but: 0
      Targets:
        - Id: AlertsTopicFailureTarget
          Arn: !Ref AlertsTopic
          Input: !Sub '"${ProjectName}: BambooHR->NovaLXP sync FAILED."'

  AlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref AlertsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventBridgePublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref AlertsTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/${ProjectName}-task-*'

Outputs:
  VpcId:
    Description: VPC ID used by the ECS task network configuration.
    Value: !Ref VpcId
  RepositoryUri:
    Description: ECR repository URI for docker push.
    Value: !GetAtt EcrRepository.RepositoryUri
  ClusterArn:
    Description: ECS cluster ARN.
    Value: !GetAtt EcsCluster.Arn
  StateTableName:
    Description: DynamoDB state table name.
    Value: !Ref StateTable
  BambooSecretArn:
    Description: Secrets Manager ARN for BambooHR key.
    Value: !Ref BambooSecret
  MoodleSecretArn:
    Description: Secrets Manager ARN for Moodle token.
    Value: !Ref MoodleSecret
  AlertsTopicArn:
    Description: SNS topic ARN for notifications.
    Value: !Ref AlertsTopic
